### PR TITLE
fix(next-international): preserve cookies in the middleware

### LINKED ISSUE #212: Cookies are not being included into the response header when "redirect" is performed (Server Action)
**Describe the bug**
I'm using the brand new "Server Actions" feature from 13.5. My server action just checks a dumb password, sets a cookie login=true and redirect the browser. However, the redirect ('/') doesn't include the "login" cookie. I've reproduced this issue with a brand new next-app project, introducing first the server action and working as expected and then adding the next-international functionality, resulting on the described problem/bug. 

**To Reproduce**
1. Clone the public repo with the described scenario ready (next-international + Server Action)
[test repo](https://github.com/ofranquesa/redirect-bug-next-international.git)
2. Go to "/" -> you will be redirected to /de/password
3. Introduce a correct password

**Expected behavior**
1.  Cookie "login" should be set in user's browser
2. User should be redirected to "/"

**Current behavior**
Post request response is not including the SET-COOKIE header for the cookie "login"

**About (please complete the following information):**
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
Binaries:
  Node: 16.16.0
  npm: 8.11.0
  Yarn: N/A
  pnpm: 7.9.0
Relevant Packages:
  next: 13.5.4
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A

**Additional context**

### PR DESCRIPTION
**Pull request by Yovach**
Fixes #212 

The `response` from `NextResponse.next` and `NextResponse.redirect` doesn't contains any cookies except the `Next-Locale` set by the middleware.

At first, I wanted to clone the `headers` but this added a lot of elements that were not included in the basic Server Actions

EDIT: I've just noticed that the "Set-Cookie" header was defined for each request, which isn't great.

### CODE REVIEW

**Comment by Yovach** [comment]
I checked and it shouldn't be a problem.

We can use the `init` parameter of NextResponse.redirect and NextResponse.rewrite but it'll pass all headers

File: packages/next-international/src/app/middleware/index.ts [hunk 1]
```diff
@@ -13,25 +13,26 @@ export function createI18nMiddleware<const Locales extends readonly string[]>(co
...
+        cloneCookies(request, response);
         return addLocaleToResponse(response, locale);
       } else {
         if (!['redirect', 'rewriteDefault'].includes(strategy)) {
           warn(`Invalid urlMappingStrategy: ${strategy}. Defaulting to redirect.`);
         }
 
-        const response = NextResponse.redirect(mappedUrl);
+        const response = NextResponse.redirect(requestUrl);
+        cloneCookies(request, response);
```
Comment (QuiiBz) [inline packages/next-international/src/app/middleware/index.ts:29]: We can probably move the `cloneCookies` call inside `addLocaleToResponse` to avoid duplicating it in many places.

**Review by QuiiBz — CHANGES_REQUESTED** [review]
Thanks! This seems like acceptable changes, I'll try the changes in an app before merging. Also thanks for the added documentation!

I only have one small suggestion:

File: packages/next-international/src/app/middleware/index.ts (hunk 1 above)
Comment (Yovach) [reply packages/next-international/src/app/middleware/index.ts]: I've moved the `cloneCookies` code to `addLocaleToResponse`.
Thanks

**Comment by Yovach** [comment]
The fact that `Set-Cookie` is set on each request is probably an issue because it'll break sites that are using Cookie parameters.

I just noticed that this also removes things like "HttpOnly" and "Secure" so the PR doesn't seems to be ready yet :/

**Comment by Yovach** [comment]
With my latest commit, the problem seems to have been solved as the Next-Locale cookie is only applied if necessary. I've tried this when we change the locale by url (http://localhost:3000/en => http://localhost:3000/fr) and it doesn't clear my current cookies.

**Review by QuiiBz — APPROVED** [review]
I just tried and everything seems to be working as expected, thanks!

I'll merge and make a pre-release before landing this change officially, to make sure we don't break anything.
