### PR TITLE
fix: execute function in I18nProviderWrapper instead of I18nProvider

### LINKED ISSUE #290: The PAGE CRASHES when you add I18nProviderClient and write in input control
**Describe the bug**
When you interact with an input in a client component wrapped by an I18nProviderClient before the dictionary has finished loading, the page crashes

**To Reproduce**
Use the project in codesandbox that provides the documentation, add an input control in the client component

[https://codesandbox.io/p/sandbox/jovial-paper-skkprk?file=%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A1%2C1](url)

1.- add `<input autoFocus />` to the client component
2.- Reload the page and write immediately

**Expected behavior**
the page should not crash.

**Screenshots**
image

**About (please complete the following information):**
 - next-international version 1.1.3
 - Next.js version 14 and 13.5

**Additional context**
If you wait for the dictionary to finish loading completely, everything works perfectly.

### PR DESCRIPTION
**Pull request by Yovach**
Closes #290 

With this fix, I wasn't able to reproduce the crash.

## What is this PR ?
It moves the call of `() => import("./en")` from `I18nProvider` to `I18nProviderWrapper`.

I changed this because according to the React documentation of `use` hook (https://react.dev/reference/react/use#streaming-data-from-server-to-client), the promise is executed and passed as a prop from the parent but awaited in the child.

### CODE REVIEW

File: examples/next-app/locales/client.ts [hunk 1]
```diff
@@ -4,14 +4,8 @@ import { createI18nClient } from 'next-international/client';
...
-      en: async () => {
-        await new Promise(resolve => setTimeout(resolve, 100));
-        return import('./en');
-      },
-      fr: async () => {
-        await new Promise(resolve => setTimeout(resolve, 100));
-        return import('./fr');
-      },
+      en: () => import('./en'),
+      fr: () => import('./fr'),
```
Comment (QuiiBz) [inline examples/next-app/locales/client.ts:8]: Can we keep this artificial delay? It's helpful to make sure we don't have any layout shifts / unwanted loaded when changing locale.

File: packages/next-international/src/app/client/create-i18n-provider-client.tsx [hunk 2]
```diff
@@ -21,21 +23,9 @@ export function createI18nProviderClient<Locale extends BaseLocale>(
...
-        notFound();
-      }
-
-      clientLocale = use(newLocale()).default;
-      localesCache.set(locale, clientLocale);
-    }
-
+  function I18nProvider({ locale, importLocale, children }: I18nProviderProps) {
+    const clientLocale = use(importLocale).default as Record<string, unknown>;
+    localesCache.set(locale, clientLocale);
```
Comment (QuiiBz) [inline packages/next-international/src/app/client/create-i18n-provider-client.tsx:28]: We likely don't need this `localesCache` anymore.

**Review by QuiiBz — CHANGES_REQUESTED** [review]
Thank you so much! Just tried and everything seems to be working as expected. Some suggestions:

File: examples/next-app/locales/client.ts (hunk 1 above)
Comment (Yovach) [reply examples/next-app/locales/client.ts:8]: I've done a few tests and as the `changeLocale` function does the following : import the translations from the next locale, then push the new locale to the URL and refresh the page

I don't think we'll have any layout shifts because the result of `import` is cached so it'll be reused.

I've made a video to compare with and without the artificial delay

https://github.com/QuiiBz/next-international/assets/31007601/f28132ff-201b-4257-8ad8-8d5425f2b9a1

Comment (QuiiBz) [reply examples/next-app/locales/client.ts:8]: This artificial delay allows us to see that the suspense boundary is triggered when we switch to another locale, which we absolutely don't want to happen, and should also prevent https://github.com/QuiiBz/next-international/issues/208.

Comment (Yovach) [reply examples/next-app/locales/client.ts]: oh ok, I re-added the promises in `() => import`.
I didn't know about this issue, sorry

**Review by QuiiBz — CHANGES_REQUESTED** [review]
Thanks for the update. Unfortunately adding back the artificial delay shows that we now have a loading state when switching locale in client components, which we don't want:

https://github.com/QuiiBz/next-international/assets/43268759/7aa82ca5-3307-4f91-8882-5178b371452a

I believe we'll need to add back the `localesCache`. `use()` always triggers suspense so we should only use it when loading the page for the first time.

**Comment by Yovach** [comment]
> Thanks for the update. Unfortunately adding back the artificial delay shows that we now have a loading state when switching locale in client components, which we don't want:
> 
>  Screen.Recording.2023-12-23.at.08.57.47.mov 
> I believe we'll need to add back the `localesCache`. `use()` always triggers suspense so we should only use it when loading the page for the first time.

Based on your feedback, the `I18nProvider` now checks if there's a cached value for the current `locale`, otherwise it'll call the `use` hook with the import and store the result in the `localesCache` variable.

I've also added a check in `changeLocale` to execute the call the import function only if the `newLocale` is supported.

I think in the `client.ts`, we can add a parameter here : 
```typescript
// locales/client.ts

export const { useI18n, useScopedI18n, I18nProviderClient, useChangeLocale, defineLocale, useCurrentLocale } =
  createI18nClient(
    {
      en: async (isChanging: boolean = false) => { // <---- HERE
        if (!isChanging) {
          await new Promise(resolve => setTimeout(resolve, 100));
        }
        return import('./en');
      },
      fr: async (isChanging: boolean = false) => { // <---- HERE
        if (!isChanging) {
          await new Promise(resolve => setTimeout(resolve, 100));
        }
        return import('./fr');
      },
    },
    {
      // Uncomment to set base path
      // basePath: '/base',
      // Uncomment to use custom segment name
      // segmentName: 'locale',
      // Uncomment to set fallback locale
      // fallbackLocale: en,
    },
  );
```

and in the 
```typescript
// packages/next-international/src/app/client/create-use-change-locale.ts
export function createUseChangeLocale<LocalesKeys>(
  useCurrentLocale: () => LocalesKeys,
  locales: ImportedLocales,
  config: I18nClientConfig,
) {
  return function useChangeLocale(changeLocaleConfig?: I18nChangeLocaleConfig) {
    const { push, refresh } = useRouter();
    const currentLocale = useCurrentLocale();
    const path = usePathname();
    // We call the hook conditionally to avoid always opting out of Static Rendering.
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const searchParams = changeLocaleConfig?.preserveSearchParams ? useSearchParams().toString() : undefined;
    const finalSearchParams = searchParams ? `?${searchParams}` : '';

    let pathWithoutLocale = path;

    if (config.basePath) {
      pathWithoutLocale = pathWithoutLocale.replace(config.basePath, '');
    }

    if (pathWithoutLocale.startsWith(`/${currentLocale}/`)) {
      pathWithoutLocale = pathWithoutLocale.replace(`/${currentLocale}/`, '/');
    } else if (pathWithoutLocale === `/${currentLocale}`) {
      pathWithoutLocale = '/';
    }

    return function changeLocale(newLocale: LocalesKeys) {
      const importFnLocale = locales[newLocale as keyof typeof locales];
      if (!importFnLocale) {
        warn(`The locale '${newLocale}' is not supported.`);
        return;
      }

      importFnLocale(true).then(module => { // <---- HERE
        localesCache.set(newLocale as string, module.default);
        push(`/${newLocale}${pathWithoutLocale}${finalSearchParams}`);
        refresh();
      });
    };
  };
}
```

We don't need to wait for 100ms when changing the locale from the client

**Review by QuiiBz — APPROVED** [review]
LGTM, thanks!

There's no need for `isChanging` for now, this is an implementation detail that shouldn't be exposed to the user. And keeping the timeout is very important in this example, to reveal issues like the [one above](https://github.com/QuiiBz/next-international/pull/316#pullrequestreview-1795413088) in slow networks.
